

from conf import (
    FACE_ATTENDANCE_PATH, FACE_ATTENDANCE_OLD_DIR,
    VOSK_WORLD_PATH, VOSK_WORLD_OLD_DIR,
    YAMNET_INDICES_PATH,YAMNET_INDICES_OLD_DIR,
    YOLO_CLASSEC_PATH, YOLO_CLASSEC_OLD_DIR
)
from load import get_dated_path